export const SET_MESSAGES = 'SET_MESSAGES';
export const TRY_AUTH = 'TRY_AUTH';
export const REGISTER_UID = 'REGISTER_UID';
export const REGISTER_NICKNAME = 'REGISTER_NICKNAME';
export const SET_INDIVIDUAL_MESSAGES = 'SET_INDIVIDUAL_MESSAGES';
export const SET_DEALS = 'SET_DEALS'
