platform :ios, '9.0'

target 'SoySauce' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  # Required by RNFirebase
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'Firebase/Auth'
  pod 'Firebase/Messaging'
  pod 'Firebase/Messaging'


#  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'SoySauceTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
